### ISSUE TITLE
Buttons dont open links

### ISSUE THREAD

**Issue by GENIUS12345AB** [Senophyx/Discord-RPC#14]
when i click on the button it doesnt open the link.

**Comment by Senophyx** [comment]
Hello! Can you provide Discord-RPC version and full code that you are using? So I can analyze your problem.

**Comment by GENIUS12345AB** [comment]
i checked its a discord bug thanks fot the help

**Comment by Senophyx** [comment]
Glad to hear it! Thank you for using Discord-RPC :)
