### ISSUE TITLE
Can't see RPC in discord app

### ISSUE THREAD

**Issue by DipeshAggarwal** [Senophyx/Discord-RPC#25]
Hey.
I have setup everything, even created the app, but I can't see the status update in discord.
Here is the debug log:

```
2024-03-28 20:28:43 :: [DEBUG @ presence.py._setup:137] :: Connected to \\?\pipe\discord-ipc-0
2024-03-28 20:28:43 :: [DEBUG @ presence.py._send:164] :: {'v': 1, 'client_id': ''}
2024-03-28 20:28:43 :: [DEBUG @ presence.py._recv:156] :: {'cmd': 'DISPATCH', 'data': {'v': 1, 'config': {'cdn_host': 'cdn.discordapp.com', 'api_endpoint': '//discord.com/api', 'environment': 'production'}, 'user': {'id': '', 'username': '', 'discriminator': '0', 'global_name': '', 'avatar': None, 'avatar_decoration_data': None, 'bot': False, 'flags': 32, 'premium_type': 0}}, 'evt': 'READY', 'nonce': None}
2024-03-28 20:28:43 :: [INFO @ presence.py.handshake:181] :: Connected to account ()
{'cmd': 'SET_ACTIVITY', 'args': {'pid': 19396, 'activity': {'state': 'Test', 'details': 'Test'}}, 'nonce': '221c576b-ba14-4fc9-a5d1-d7381d02e8df'}
2024-03-28 20:28:43 :: [DEBUG @ presence.py._send:164] :: {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19396, 'activity': {'state': 'Test', 'details': 'Test'}}, 'nonce': '221c576b-ba14-4fc9-a5d1-d7381d02e8df'}
2024-03-28 20:28:43 :: [INFO @ presence.py.set_activity:100] :: RPC set
```

Do you know what might b going wrong?

**Comment by Senophyx** [comment]
Hello! Sorry for late respond, kinda busy.

Anyway, that's very strange. Because the client_id, username and global name must appear in the debug console.
Did you make sure your Discord app is opened? also can i see the full code?

**Comment by DipeshAggarwal** [comment]
Hey. client_id, username and global name were in the debug console. I just redacted them.

Code:
```python
    import discordrpc

    rpc = discordrpc.RPC(app_id=1234567890, debug=True)
    rpc.set_activity(
        state="Test",
        details="Test",
        large_image="default"
    )
```

**Comment by Senophyx** [comment]
I see! Make sure you use `rpc.run()` at the end of your file to loop the rpc.

See [here](https://github.com/Senophyx/Discord-RPC/blob/main/DOCS.md#class-discordrpcrpc) and scroll down to `method RPC.run()`.

**Comment by DipeshAggarwal** [comment]
I still cannot see the RPC status in Discord.

Full code

```python
    import discordrpc

    rpc = discordrpc.RPC(app_id=1222892175671427173, debug=True)
    rpc.set_activity(
        state="Test",
        details="Test",
        large_image="default"
    )

    rpc.run()
```

**Comment by DipeshAggarwal** [comment]
I still cannot see the RPC status in Discord.

Full code

```python
    import discordrpc

    rpc = discordrpc.RPC(app_id=1234567890, debug=True)
    rpc.set_activity(
        state="Test",
        details="Test",
        large_image="default"
    )

    rpc.run()
```

**Comment by Senophyx** [comment]
That's really weird. Can your friends see it?

**Comment by DipeshAggarwal** [comment]
No one can.

**Comment by Senophyx** [comment]
Humm weird. What OS do you use?

**Comment by DipeshAggarwal** [comment]
Windows 11.

**Comment by Senophyx** [comment]
have you tried waiting? maybe because of a connection issue. I've never experienced anything like that, because it's usually instant. The important thing is that the code is correct and Discord is running

**Comment by DipeshAggarwal** [comment]
I have tried waiting for over 5 minutes. Discord is running the entire time.

Should I wait for a longer time?

**Comment by Senophyx** [comment]
haha that's enough. have you tried other libs? because only a few, almost no one experiences the same situation as you, so I don't know for sure what the problem is.

**Comment by DipeshAggarwal** [comment]
I will try to use other libs and report back to you. Any ones that you recommend?

**Comment by Senophyx** [comment]
you can use [pypresence](https://github.com/qwertyquerty/pypresence), almost the same as Discord-RPC.

**Comment by Senophyx** [comment]
How is the result? I will close this issue and consider this issue resolved if there is no confirmation within 12 hours.

**Comment by DipeshAggarwal** [comment]
Yeah. Doesn't look like it's related to the lib. Same result with PyPresence and a few othere.

Do you have any idea what could be going wrong? Is there something specific I need to do in the application portal?

**Comment by Senophyx** [comment]
Just copy the app ID from discord dev portal, no need to mess around anymore. Maybe try updating the Discord application and look at the presence settings in the Discord application (game presence).

**Comment by DipeshAggarwal** [comment]
So it was my fault. Somehow Presence was turned off in settings.

**Comment by Senophyx** [comment]
Great! Thank goodness it wasn't from Discord-RPC. Well, have fun then! Thank you for continuing to report throughout this issue, and thank you also for using my package. 👍🏻
